development: &development
  store: 'local'
  s3_media_root: https://rails-base-application-stage-media.s3.amazonaws.com
  s3_media_bucket: rails-base-application
  s3_media_region: <%= Rails.application.credentials[Rails.env.to_sym][:AWS_REGION] %>
  s3_access_key_id: <%= Rails.application.credentials[Rails.env.to_sym][:S3_ACCESS_KEY_ID] %>
  s3_secret_access_key: <%= Rails.application.credentials[Rails.env.to_sym][:S3_SECRET_ACCESS_KEY] %>
  cloufront_url: https://d2rwu95fjsfpjp.cloudfront.net

test: &development
  store: 'local'
  s3_media_root: https://rails-base-application-stage-media.s3.amazonaws.com
  s3_media_bucket: rails-base-application
  s3_media_region: <%= Rails.application.credentials[Rails.env.to_sym][:AWS_REGION] %>
  s3_access_key_id: <%= Rails.application.credentials[Rails.env.to_sym][:S3_ACCESS_KEY_ID] %>
  s3_secret_access_key: <%= Rails.application.credentials[Rails.env.to_sym][:S3_SECRET_ACCESS_KEY] %>
  cloufront_url: https://d2rwu95fjsfpjp.cloudfront.net

staging: &development
  store: 'local'
  s3_media_root: https://rails-base-application-stage-media.s3.amazonaws.com
  s3_media_bucket: rails-base-application
  s3_media_region: <%= Rails.application.credentials[Rails.env.to_sym][:AWS_REGION] %>
  s3_access_key_id: <%= Rails.application.credentials[Rails.env.to_sym][:S3_ACCESS_KEY_ID] %>
  s3_secret_access_key: <%= Rails.application.credentials[Rails.env.to_sym][:S3_SECRET_ACCESS_KEY] %>
  cloufront_url: https://d2rwu95fjsfpjp.cloudfront.net